---
- name: Install PostgreSQL
  hosts: desenvolvimento:producao
  gather_facts: no
  become: yes
  pre_tasks:
    - name: 'Install python2'
      raw: apt-get -y install python-simplejson

  tasks:
    - name: Install postgres
      apt: pkg={{ item }} state=installed
      with_items:
        - postgresql-common
        - postgresql-contrib
        - postgresql
        - libpq-dev
        - python-psycopg2
      tags:
        - packages
    - name: PostgreSQL | Ensure PostgreSQL is running
      service:
        name: postgresql
        state: started
    - name: Local PostgreSQL - Active the 'unaccent' extension on databases
      become: yes
      become_user: postgres
      postgresql_ext: name=unaccent db=template0
